/*******************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only
* intended for use with Renesas products. No other uses are authorized. This
* software is owned by Renesas Electronics Corporation and is protected under
* all applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
* LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
* AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
* FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
* ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software
* and to discontinue the availability of this software. By using this software,
* you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
* Copyright (C) 2018 Renesas Electronics Corporation. All rights reserved.
*******************************************************************************/ 
/*******************************************************************************
* Rev: 1.00
* Description : IO bitmask header
*******************************************************************************/

#ifndef RTC_BCNT_IOBITMASK_H
#define RTC_BCNT_IOBITMASK_H


/* ==== Mask values for IO registers ==== */

#define RTC_BCNT_R64CNT_F64HZ                                                  (0x01u)
#define RTC_BCNT_R64CNT_F64HZ_SHIFT                                            (0u)
#define RTC_BCNT_R64CNT_F32HZ                                                  (0x02u)
#define RTC_BCNT_R64CNT_F32HZ_SHIFT                                            (1u)
#define RTC_BCNT_R64CNT_F16HZ                                                  (0x04u)
#define RTC_BCNT_R64CNT_F16HZ_SHIFT                                            (2u)
#define RTC_BCNT_R64CNT_F8HZ                                                   (0x08u)
#define RTC_BCNT_R64CNT_F8HZ_SHIFT                                             (3u)
#define RTC_BCNT_R64CNT_F4HZ                                                   (0x10u)
#define RTC_BCNT_R64CNT_F4HZ_SHIFT                                             (4u)
#define RTC_BCNT_R64CNT_F2HZ                                                   (0x20u)
#define RTC_BCNT_R64CNT_F2HZ_SHIFT                                             (5u)
#define RTC_BCNT_R64CNT_F1HZ                                                   (0x40u)
#define RTC_BCNT_R64CNT_F1HZ_SHIFT                                             (6u)
#define RTC_BCNT_BCNT0_BCNT                                                    (0xFFu)
#define RTC_BCNT_BCNT0_BCNT_SHIFT                                              (0u)
#define RTC_BCNT_BCNT1_BCNT                                                    (0x00u)
#define RTC_BCNT_BCNT1_BCNT_SHIFT                                              (0u)
#define RTC_BCNT_BCNT2_BCNT                                                    (0x00u)
#define RTC_BCNT_BCNT2_BCNT_SHIFT                                              (0u)
#define RTC_BCNT_BCNT3_BCNT                                                    (0x00u)
#define RTC_BCNT_BCNT3_BCNT_SHIFT                                              (0u)
#define RTC_BCNT_RDAYCNT_DATE1                                                 (0x0Fu)
#define RTC_BCNT_RDAYCNT_DATE1_SHIFT                                           (0u)
#define RTC_BCNT_RDAYCNT_DATE10                                                (0x30u)
#define RTC_BCNT_RDAYCNT_DATE10_SHIFT                                          (4u)
#define RTC_BCNT_RMONCNT_MON1                                                  (0x0Fu)
#define RTC_BCNT_RMONCNT_MON1_SHIFT                                            (0u)
#define RTC_BCNT_RMONCNT_MON10                                                 (0x10u)
#define RTC_BCNT_RMONCNT_MON10_SHIFT                                           (4u)
#define RTC_BCNT_RYRCNT_YR1                                                    (0x000Fu)
#define RTC_BCNT_RYRCNT_YR1_SHIFT                                              (0u)
#define RTC_BCNT_RYRCNT_YR10                                                   (0x00F0u)
#define RTC_BCNT_RYRCNT_YR10_SHIFT                                             (4u)
#define RTC_BCNT_BCNT0AR_BCNTAR                                                (0xFFu)
#define RTC_BCNT_BCNT0AR_BCNTAR_SHIFT                                          (0u)
#define RTC_BCNT_BCNT1AR_BCNTAR                                                (0x00u)
#define RTC_BCNT_BCNT1AR_BCNTAR_SHIFT                                          (0u)
#define RTC_BCNT_BCNT2AR_BCNTAR                                                (0x00u)
#define RTC_BCNT_BCNT2AR_BCNTAR_SHIFT                                          (0u)
#define RTC_BCNT_BCNT3AR_BCNTAR                                                (0x00u)
#define RTC_BCNT_BCNT3AR_BCNTAR_SHIFT                                          (0u)
#define RTC_BCNT_BCNT0AER_ENB                                                  (0xFFu)
#define RTC_BCNT_BCNT0AER_ENB_SHIFT                                            (0u)
#define RTC_BCNT_BCNT1AER_ENB                                                  (0x00u)
#define RTC_BCNT_BCNT1AER_ENB_SHIFT                                            (0u)
#define RTC_BCNT_BCNT2AER_ENB                                                  (0x0000u)
#define RTC_BCNT_BCNT2AER_ENB_SHIFT                                            (0u)
#define RTC_BCNT_BCNT3AER_ENB                                                  (0x00u)
#define RTC_BCNT_BCNT3AER_ENB_SHIFT                                            (0u)
#define RTC_BCNT_RSR_AF                                                        (0x01u)
#define RTC_BCNT_RSR_AF_SHIFT                                                  (0u)
#define RTC_BCNT_RSR_CF                                                        (0x02u)
#define RTC_BCNT_RSR_CF_SHIFT                                                  (1u)
#define RTC_BCNT_RSR_PF                                                        (0x04u)
#define RTC_BCNT_RSR_PF_SHIFT                                                  (2u)
#define RTC_BCNT_RCR1_AIE                                                      (0x01u)
#define RTC_BCNT_RCR1_AIE_SHIFT                                                (0u)
#define RTC_BCNT_RCR1_CIE                                                      (0x02u)
#define RTC_BCNT_RCR1_CIE_SHIFT                                                (1u)
#define RTC_BCNT_RCR1_PIE                                                      (0x04u)
#define RTC_BCNT_RCR1_PIE_SHIFT                                                (2u)
#define RTC_BCNT_RCR1_PES                                                      (0xF0u)
#define RTC_BCNT_RCR1_PES_SHIFT                                                (4u)
#define RTC_BCNT_RCR2_START                                                    (0x01u)
#define RTC_BCNT_RCR2_START_SHIFT                                              (0u)
#define RTC_BCNT_RCR2_RESET                                                    (0x02u)
#define RTC_BCNT_RCR2_RESET_SHIFT                                              (1u)
#define RTC_BCNT_RCR2_ADJ30                                                    (0x04u)
#define RTC_BCNT_RCR2_ADJ30_SHIFT                                              (2u)
#define RTC_BCNT_RCR2_AADJE                                                    (0x10u)
#define RTC_BCNT_RCR2_AADJE_SHIFT                                              (4u)
#define RTC_BCNT_RCR2_AADJP                                                    (0x20u)
#define RTC_BCNT_RCR2_AADJP_SHIFT                                              (5u)
#define RTC_BCNT_RCR2_HR24                                                     (0x40u)
#define RTC_BCNT_RCR2_HR24_SHIFT                                               (6u)
#define RTC_BCNT_RCR2_CNTMD                                                    (0x80u)
#define RTC_BCNT_RCR2_CNTMD_SHIFT                                              (7u)
#define RTC_BCNT_RCR3_RTCEN                                                    (0x01u)
#define RTC_BCNT_RCR3_RTCEN_SHIFT                                              (0u)
#define RTC_BCNT_RCR4_RCKSEL                                                   (0x01u)
#define RTC_BCNT_RCR4_RCKSEL_SHIFT                                             (0u)
#define RTC_BCNT_RFRH_RFC                                                      (0x0001u)
#define RTC_BCNT_RFRH_RFC_SHIFT                                                (0u)
#define RTC_BCNT_RFRL_RFC                                                      (0xFFFFu)
#define RTC_BCNT_RFRL_RFC_SHIFT                                                (0u)
#define RTC_BCNT_RADJ_ADJ                                                      (0x3Fu)
#define RTC_BCNT_RADJ_ADJ_SHIFT                                                (0u)
#define RTC_BCNT_RADJ_PMADJ                                                    (0xC0u)
#define RTC_BCNT_RADJ_PMADJ_SHIFT                                              (6u)
#define RTC_BCNT_RTEST_TEST0                                                   (0x01u)
#define RTC_BCNT_RTEST_TEST0_SHIFT                                             (0u)
#define RTC_BCNT_RTEST_TEST1                                                   (0x02u)
#define RTC_BCNT_RTEST_TEST1_SHIFT                                             (1u)
#define RTC_BCNT_RTEST_TEST2                                                   (0x04u)
#define RTC_BCNT_RTEST_TEST2_SHIFT                                             (2u)
#define RTC_BCNT_RTEST_TEST3                                                   (0x08u)
#define RTC_BCNT_RTEST_TEST3_SHIFT                                             (3u)
#define RTC_BCNT_RKEY_KEY                                                      (0xFFu)
#define RTC_BCNT_RKEY_KEY_SHIFT                                                (0u)
#define RTC_BCNT_RTCCR0_TCCT                                                   (0x03u)
#define RTC_BCNT_RTCCR0_TCCT_SHIFT                                             (0u)
#define RTC_BCNT_RTCCR0_TCST                                                   (0x04u)
#define RTC_BCNT_RTCCR0_TCST_SHIFT                                             (2u)
#define RTC_BCNT_RTCCR0_TCNF                                                   (0x30u)
#define RTC_BCNT_RTCCR0_TCNF_SHIFT                                             (4u)
#define RTC_BCNT_RTCCR0_TCEN                                                   (0x80u)
#define RTC_BCNT_RTCCR0_TCEN_SHIFT                                             (7u)
#define RTC_BCNT_RTCCR1_TCCT                                                   (0x03u)
#define RTC_BCNT_RTCCR1_TCCT_SHIFT                                             (0u)
#define RTC_BCNT_RTCCR1_TCST                                                   (0x04u)
#define RTC_BCNT_RTCCR1_TCST_SHIFT                                             (2u)
#define RTC_BCNT_RTCCR1_TCNF                                                   (0x30u)
#define RTC_BCNT_RTCCR1_TCNF_SHIFT                                             (4u)
#define RTC_BCNT_RTCCR1_TCEN                                                   (0x80u)
#define RTC_BCNT_RTCCR1_TCEN_SHIFT                                             (7u)
#define RTC_BCNT_RTCCR2_TCCT                                                   (0x03u)
#define RTC_BCNT_RTCCR2_TCCT_SHIFT                                             (0u)
#define RTC_BCNT_RTCCR2_TCST                                                   (0x04u)
#define RTC_BCNT_RTCCR2_TCST_SHIFT                                             (2u)
#define RTC_BCNT_RTCCR2_TCNF                                                   (0x30u)
#define RTC_BCNT_RTCCR2_TCNF_SHIFT                                             (4u)
#define RTC_BCNT_RTCCR2_TCEN                                                   (0x80u)
#define RTC_BCNT_RTCCR2_TCEN_SHIFT                                             (7u)
#define RTC_BCNT_BCNT0CP0_BCNTCP0                                              (0xFFu)
#define RTC_BCNT_BCNT0CP0_BCNTCP0_SHIFT                                        (0u)
#define RTC_BCNT_BCNT1CP0_BCNTCP0                                              (0x00u)
#define RTC_BCNT_BCNT1CP0_BCNTCP0_SHIFT                                        (0u)
#define RTC_BCNT_BCNT2CP0_BCNTCP0                                              (0x00u)
#define RTC_BCNT_BCNT2CP0_BCNTCP0_SHIFT                                        (0u)
#define RTC_BCNT_BCNT3CP0_BCNTCP0                                              (0x00u)
#define RTC_BCNT_BCNT3CP0_BCNTCP0_SHIFT                                        (0u)
#define RTC_BCNT_RMONCP0_MON1                                                  (0x0Fu)
#define RTC_BCNT_RMONCP0_MON1_SHIFT                                            (0u)
#define RTC_BCNT_RMONCP0_MON10                                                 (0x10u)
#define RTC_BCNT_RMONCP0_MON10_SHIFT                                           (4u)
#define RTC_BCNT_BCNT0CP1_BCNTCP1                                              (0xFFu)
#define RTC_BCNT_BCNT0CP1_BCNTCP1_SHIFT                                        (0u)
#define RTC_BCNT_BCNT1CP1_BCNTCP1                                              (0x00u)
#define RTC_BCNT_BCNT1CP1_BCNTCP1_SHIFT                                        (0u)
#define RTC_BCNT_BCNT2CP1_BCNTCP1                                              (0x00u)
#define RTC_BCNT_BCNT2CP1_BCNTCP1_SHIFT                                        (0u)
#define RTC_BCNT_BCNT3CP1_BCNTCP1                                              (0x00u)
#define RTC_BCNT_BCNT3CP1_BCNTCP1_SHIFT                                        (0u)
#define RTC_BCNT_RMONCP1_MON1                                                  (0x0Fu)
#define RTC_BCNT_RMONCP1_MON1_SHIFT                                            (0u)
#define RTC_BCNT_RMONCP1_MON10                                                 (0x10u)
#define RTC_BCNT_RMONCP1_MON10_SHIFT                                           (4u)
#define RTC_BCNT_BCNT0CP2_BCNTCP2                                              (0xFFu)
#define RTC_BCNT_BCNT0CP2_BCNTCP2_SHIFT                                        (0u)
#define RTC_BCNT_BCNT1CP2_BCNTCP2                                              (0x00u)
#define RTC_BCNT_BCNT1CP2_BCNTCP2_SHIFT                                        (0u)
#define RTC_BCNT_BCNT2CP2_BCNTCP2                                              (0x00u)
#define RTC_BCNT_BCNT2CP2_BCNTCP2_SHIFT                                        (0u)
#define RTC_BCNT_BCNT3CP2_BCNTCP2                                              (0x00u)
#define RTC_BCNT_BCNT3CP2_BCNTCP2_SHIFT                                        (0u)
#define RTC_BCNT_RMONCP2_MON1                                                  (0x0Fu)
#define RTC_BCNT_RMONCP2_MON1_SHIFT                                            (0u)
#define RTC_BCNT_RMONCP2_MON10                                                 (0x10u)
#define RTC_BCNT_RMONCP2_MON10_SHIFT                                           (4u)

#endif
